
mex  bet2.cpp ...
    ...cprob
    ./cprob/bdtr.c ./cprob/btdtr.c ./cprob/chdtr.c ./cprob/drand.c ./cprob/expx2.c ./cprob/fdtr.c ./cprob/gamma.c ./cprob/gdtr.c ...
    ./cprob/igam.c ./cprob/igami.c ./cprob/incbet.c ./cprob/incbi.c ./cprob/mtherr.c ./cprob/nbdtr.c ./cprob/ndtr.c ./cprob/ndtri.c ./cprob/pdtr.c ...
    ./cprob/stdtr.c ./cprob/unity.c ./cprob/polevl.c ./cprob/const.c ./cprob/xmath.c...
    ...fslio
    ./fslio/fslio.c...
    ...meshclass
    ./meshclass/point.cpp ./meshclass/mpoint.cpp ./meshclass/triangle.cpp ./meshclass/mesh.cpp ./meshclass/pt_special.cpp ./meshclass/profile.cpp... 
    ...miscmaths
    ./miscmaths/miscmaths.cc ./miscmaths/optimise.cc ./miscmaths/miscprob.cc ./miscmaths/kernel.cc ...
    ./miscmaths/histogram.cc ./miscmaths/base2z.cc ./miscmaths/t2z.cc ./miscmaths/f2z.cc ...
    ./miscmaths/minimize.cc ./miscmaths/cspline.cc ./miscmaths/sparse_matrix.cc ./miscmaths/sparsefn.cc ...
    ./miscmaths/rungekutta.cc ./miscmaths/nonlin.cpp ./miscmaths/bfmatrix.cpp...
    ...newimage
    ./newimage/lazy.cc ./newimage/newimage.cc ./newimage/generalio.cc ./newimage/newimagefns.cc ...
    ./newimage/complexvolume.cc ./newimage/imfft.cc...
    ...newmat
    ./newmat/bandmat.cpp ./newmat/cholesky.cpp ./newmat/evalue.cpp ./newmat/fft.cpp ./newmat/hholder.cpp     ...
    ./newmat/jacobi.cpp ./newmat/myexcept.cpp ./newmat/newmat1.cpp ./newmat/newmat2.cpp ./newmat/newmat3.cpp       ...
    ./newmat/newmat4.cpp ./newmat/newmat5.cpp ./newmat/newmat6.cpp ./newmat/newmat7.cpp ./newmat/newmat8.cpp       ...
    ./newmat/newmat9.cpp ./newmat/newmatex.cpp ./newmat/newmatnl.cpp ./newmat/newmatrm.cpp ./newmat/solution.cpp   ...
    ./newmat/sort.cpp ./newmat/submat.cpp ./newmat/svd.cpp ./newmat/newfft.cpp...
    ...niftiio
    ./niftiio/nifti1_io.c...
    ...utils
    ./utils/matches.cc ./utils/functions.cc ./utils/usage.cc ./utils/check.cc ./utils/parse.cc ./utils/log.cc ./utils/time_tracer.cc...
    ...snzlib
    ./znzlib/znzlib.c...
    -v

clc
disp('Done')

%% Example
% Options.fractional_threshold = 0.5;
% Options.smooth = 1;
% Options.outline = true;
% NII=load_untouch_nii('ImgTest.nii');
% Mask = bet2(NII.img,Options);







